name: face_anim
channels:
  - iopath
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - fvcore
dependencies:
  - python==3.10
  - pytorch=2.0.0=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8
  - imageio
  - numpy
  - pyyaml
  - tensorboard
  - torchvision
  - tqdm
  - scikit-learn
  - fvcore
  - iopath
  - pip
  - pip:
    - opencv-python-headless
    - scikit-image
    - matplotlib
    - imageio
    - seaborn
    - mediapipe
    - "git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch"
    # need manual instalation - --no-index pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py310_cu118_pyt200/download.html